spring.application.name=notification-service
server.port=8087

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Environment variable support
spring.config.import=optional:file:../.env[.properties]

# Database Configuration (PostgreSQL)
# Thay URL/username/password thành thông tin CSDL của bạn (Dưới đây là thông tin mặc định theo dự án của bạn trên Render)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8pq59jtqb8s738ei6f0-a.singapore-postgres.render.com:5432/notification_db}
spring.datasource.username=${DB_USERNAME:nhat_db_server_msfu_user}
spring.datasource.password=${DB_PASSWORD:FiHPWRw3srvSHJ7LA2KvVpYAMYV8zWCG}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.addresses=amqps://ttwqpurs:V2hDVA8Wu0_xE2F59WXCbC2qQB8Ex8a6@fuji.lmq.cloudamqp.com/ttwqpurs

# SendGrid Configuration
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=gbin29901@gmail.com
