##### Service details: #####
server.port= 8811
spring.application.name= user-service
server.url= http://localhost:8811

#Client registration properties :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Data source :
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/users}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Giangminhnhat22!}
spring.datasource.driverClassName=org.postgresql.Driver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

##### HTTP #####
error.404.schema.details=The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json

# SendGrid Configuration
spring.config.import=optional:file:../.env[.properties]
spring.dotenv.directory=../
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=giangminhnhat2004@gmail.com

spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-3.1-flash-lite

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379