server:
  port: 8814

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://dpg-d84j7egjs32c739sr4n0-a.singapore-postgres.render.com:5432/payment_service_db}
    username: ${DB_USERNAME:nhat_db_server_user}
    password: ${DB_PASSWORD:yE2UWIBEcyrkosSxWWOq5Xh2tuFKcayH}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# ─── VNPAY Sandbox Configuration ───
vnpay:
  tmn-code: 0S5H1KK6
  hash-secret: H8GXZJWX0NAOG9XYEW1CVPG0H5IXN56K
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/payment/return
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
