#Server port :
server.port= 8810

#Application name :
spring.application.name= product-catalog-service

#Client registration properties :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Data source :
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_catalog}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Giangminhnhat22!}
spring.datasource.driverClassName=org.postgresql.Driver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Multipart File upload :
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Upload path (thư mục ngoài src, ngang hàng pom.xml) :
upload.path=uploads/banners
